  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
          - name: Install packages
            run: |
              cd pz-cheeseria-web-app
              npm i
          - name: Set Creds
            run: |
              cd pz-cheeseria-web-app
              git config user.name "<username>" && git config user.email "<email>"
          - name: Deploy
            run: |
              cd pz-cheeseria-web-app
              npm run deploy

