name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Print the root working directory for debugging
    - name: Print working directory
      run: |
        pwd
        ls -la

    # Setup Node.js and cache dependencies, then install and build in one step using cd
    - name: Install dependencies and build the project
      run: |
        cd pz-cheeseria-web-app
        npm ci
        npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js for deployment, install dependencies, build, and deploy in one step using cd
    - name: Install dependencies, build, and deploy
      run: |
        cd pz-cheeseria-web-app
        npm ci
        npm run build
        npm run deploy

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pz-cheeseria-web-app/dist

